language: c

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.3

sudo: required

addons:
  apt:
    packages:
      - libpam0g-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - time
      - perl
      - selinux-policy-dev

script: 
      - cd Unix && ./regress
